# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Dropbox\program\svviewer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 793)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setGeometry(QtCore.QRect(30, 20, 521, 611))
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.gridGroupBox)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 1, 1, 1)
        self.gridFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame_2.setGeometry(QtCore.QRect(600, 220, 481, 181))
        self.gridFrame_2.setObjectName("gridFrame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridFrame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 9, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 9, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 7, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 4, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 5, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 6, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridFrame_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 8, 4, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridFrame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 2, 1)
        self.label_21 = QtWidgets.QLabel(self.gridFrame_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 7, 3, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.gridFrame_2)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout_2.addWidget(self.progressBar_2, 10, 4, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridFrame_2)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 8, 1, 1, 1)
        self.gridFrame = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame.setGeometry(QtCore.QRect(600, 420, 481, 211))
        self.gridFrame.setObjectName("gridFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridFrame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridFrame)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 8, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridFrame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 7, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridFrame)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 6, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridFrame)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridFrame)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridFrame)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridFrame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 3, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridFrame)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 3, 1, 1)
        self.gridFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.gridFrame1.setGeometry(QtCore.QRect(600, 20, 481, 181))
        self.gridFrame1.setObjectName("gridFrame1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridFrame1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.gridFrame1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_4.addWidget(self.pushButton_5, 4, 5, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridFrame1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 4, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridFrame1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridFrame1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_4.addWidget(self.pushButton, 2, 4, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.gridFrame1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_4.addWidget(self.horizontalSlider_2, 4, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridFrame1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 3, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.gridFrame1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_4.addWidget(self.horizontalSlider, 2, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem8, 5, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.gridFrame1)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_4.addWidget(self.radioButton, 0, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.gridFrame1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_4.addWidget(self.radioButton_2, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridFrame1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridFrame1)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridFrame1)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 6, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridFrame1)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_4.addWidget(self.progressBar, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDisplay = QtWidgets.QMenu(self.menubar)
        self.menuDisplay.setObjectName("menuDisplay")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        MainWindow.insertToolBarBreak(self.toolBar_2)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/ooopic_1518630026.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionApply = QtWidgets.QAction(MainWindow)
        self.actionApply.setObjectName("actionApply")
        self.actionOptions = QtWidgets.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionPreview = QtWidgets.QAction(MainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/ooopic_1518630082.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon1)
        self.actionClose.setObjectName("actionClose")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/ooopic_1518630700.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon2)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("source/ooopic_1518630673.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon3)
        self.actionNext.setObjectName("actionNext")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("source/ooopic_1518630711.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAdd = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("source/ooopic_1518630690.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon5)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDisplay = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("source/ooopic_1518630729.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisplay.setIcon(icon6)
        self.actionDisplay.setObjectName("actionDisplay")
        self.actionReload = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("source/reload_24x28.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon7)
        self.actionReload.setObjectName("actionReload")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClear)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionApply)
        self.menuDisplay.addAction(self.actionOptions)
        self.menuView.addAction(self.actionPreview)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuDisplay.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionClose)
        self.toolBar.addAction(self.actionReload)
        self.toolBar.addAction(self.actionNext)
        self.toolBar.addAction(self.actionPrevious)
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionDisplay)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Display"))
        self.label_14.setText(_translate("MainWindow", "Timerange"))
        self.label_16.setText(_translate("MainWindow", "Imsize"))
        self.label_12.setText(_translate("MainWindow", "Imagename:"))
        self.label_15.setText(_translate("MainWindow", "Uvrange"))
        self.label_13.setText(_translate("MainWindow", "Spw"))
        self.label_17.setText(_translate("MainWindow", "Cell"))
        self.label_18.setText(_translate("MainWindow", "npercycle"))
        self.label_19.setText(_translate("MainWindow", "Phasecenter"))
        self.label_20.setText(_translate("MainWindow", "Stokes"))
        self.pushButton_6.setText(_translate("MainWindow", "Clean"))
        self.pushButton_2.setText(_translate("MainWindow", "Draw a Box"))
        self.label_21.setText(_translate("MainWindow", "Robust"))
        self.checkBox.setText(_translate("MainWindow", "Interactrive"))
        self.label_4.setText(_translate("MainWindow", "Correlation"))
        self.label_5.setText(_translate("MainWindow", "Frequency"))
        self.label_6.setText(_translate("MainWindow", "Spw"))
        self.label_2.setText(_translate("MainWindow", "States"))
        self.label_7.setText(_translate("MainWindow", "Time"))
        self.label_23.setText(_translate("MainWindow", "Flux"))
        self.pushButton_7.setText(_translate("MainWindow", "Draw a Box"))
        self.label_22.setText(_translate("MainWindow", "SNR"))
        self.pushButton_5.setText(_translate("MainWindow", "Save"))
        self.pushButton_4.setText(_translate("MainWindow", "Load"))
        self.pushButton_3.setText(_translate("MainWindow", "Save"))
        self.pushButton.setText(_translate("MainWindow", "Load"))
        self.label_9.setText(_translate("MainWindow", "Uvrange"))
        self.radioButton.setText(_translate("MainWindow", "Ant"))
        self.radioButton_2.setText(_translate("MainWindow", "Baseline Length"))
        self.label_8.setText(_translate("MainWindow", "Sort"))
        self.label_10.setText(_translate("MainWindow", "States"))
        self.label_11.setText(_translate("MainWindow", "Show the information  of selected baseline"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuDisplay.setTitle(_translate("MainWindow", "Display"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionApply.setText(_translate("MainWindow", "Apply"))
        self.actionOptions.setText(_translate("MainWindow", "Options"))
        self.actionPreview.setText(_translate("MainWindow", "Preview"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAdd.setText(_translate("MainWindow", "Add"))
        self.actionDisplay.setText(_translate("MainWindow", "Display"))
        self.actionReload.setText(_translate("MainWindow", "Reload"))

import sys
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
